// Code generated by dingo; DO NOT EDIT
package main

import pos "github.com/ironiclensflare/printer/pos"

type Container struct {
	Printer pos.Printer
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{}
}
func (container *Container) GetPrinter() pos.Printer {
	if container.Printer == nil {
		service := &pos.ThermalPrinter{}
		container.Printer = service
	}
	return container.Printer
}
